server:
  port: 8090
spring:
  application:
    name: actors-ms
  config:
    import: optional:configserver:http://localhost:8012
    name: UDLConfigServer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000
#          issuer-uri: http://auth-server:8000

